# Generated by Django 5.1.3 on 2026-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='comma-seprated values e.g, Django, MySql, Bootstrap', max_length=50)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
