# Generated by Django 5.1.3 on 2026-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='', help_text='Devicon class, e.g, devicon-python-plain', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiancy',
            field=models.IntegerField(choices=[(1, 'beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2),
        ),
    ]
