# Generated by Django 5.1.3 on 2026-07-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_skill_icon_class_skill_proficiancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='proficiancy',
            new_name='proficiency',
        ),
    ]
